### PR TITLE
CI: Add Windows MSYS2, MacOS and QA workflow

### PR DESCRIPTION
**Pull request by jtxa**
Additionally to the Linux builds, there's now also one on MacOS, and 3 MSYS2 based on Windows.
Also a minimal clang-tidy configuration and check was added.

### CODE REVIEW

**Comment by jtxa** [comment]
FYI: Windows needs about 7, MacOS about 6 minutes. In comparison, Linux is about 1 and a half.

**Comment by sierrafoxtrot** [comment]
All looks great. I've been scratching my head on how to do the mac build (I don't own one and was looking on ebay for something cheap...).

One overall comment is that I've been considering switching the default generator to ninja everywhere (rather than make on Linux for example). Any thoughts? Would including it here make sense given all the spots where you need to explicitly run `cmake -G ninja`?

**Comment by jtxa** [comment]
All the workflows use Ninja already. It's what I always use in combination with CMake (has its benefits, although maybe not relevant for SRecord).
I don't think there are any other calls inside the repo, apart from the `BUILDING.man` documentation.

Inside the cmake files you should not set a default generator, it's not really [possible](https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR.html) and the decision is up to the user.
Personally you can specify it in a `CMAKE_GENERATOR` environment variable, so you don't need to specify it yourself on the command line every time.

**Comment by sierrafoxtrot** [comment]
> Inside the cmake files you should not set a default generator, it's not really [possible](https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR.html) and the decision is up to the user. 

Fair call. It's my preference too but no reason to try to impose that on others (even if it were possible).

**Pull request merged**
